#! /bin/bash

mkdir -p ~/.config/i3
mkdir -p ~/.config/i3blocks
mkdir -p ~/.config/sxiv/exec

ln -snf $(realpath xinitrc) ~/.xinitrc
ln -snf $(realpath xresources) ~/.Xresources
ln -snf $(realpath i3/config) ~/.config/i3/config
ln -snf $(realpath i3blocks/config) ~/.config/i3blocks/config
ln -snf $(realpath sxiv/key-handler) ~/.config/sxiv/exec/key-handler

