#!/bin/bash

bupath=~/.cache/faw_backup/unixdev
mkdir -p $bupath

cp ~/.vimrc $bupath/vimrc
cp ~/.bashrc $bupath/bashrc
cp ~/.bash_profile $bupath/bash_profile
cp ~/.tmux.conf $bupath/tmux.conf

echo -e "\nnote: unixdev backups are stored at $bupath\n"

ln -snf $(realpath vimrc) ~/.vimrc
ln -snf $(realpath bash_profile) ~/.bash_profile
ln -snf $(realpath bashrc) ~/.bashrc
ln -snf $(realpath tmux.conf) ~/.tmux.conf

curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

