#! /bin/bash

mkdir -p ~/.config/lf
mkdir -p ~/.config/nvim

mkdir -p ~/.newsboat
mkdir -p ~/.w3m

ln -snf $(realpath bashrc) ~/.bashrc
ln -snf $(realpath bash_profile) ~/.bash_profile
ln -snf $(realpath xinitrc) ~/.xinitrc

ln -snf $(realpath neovim/init.vim) ~/.config/nvim/init.vim
ln -snf $(realpath lf/lfrc) ~/.config/lf/lfrc

ln -snf $(realpath w3m/keymap) ~/.w3m/keymap
ln -snf $(realpath newsboat/config) ~/.newsboat/config

