#! /bin/bash

mkdir -p ~/.config/kak

touch ~/.config/kak/kakrc
touch ~/.bashrc
touch ~/.tmux.conf

echo "source $(realpath kakrc)" >> ~/.config/kak/kakrc
echo "source $(realpath bashrc)" >> ~/.bashrc
echo "source-file $(realpath tmux.conf)" >> ~/.tmux.conf

