
xrdb ~/.Xresources

xwallpaper --stretch ~/.wallpaper.jpg
setxkbmap -layout us,ru -option grp:alt_shift_toggle

pulseaudio -k; pulseaudio --daemonize

pkill xcompmgr; xcompmgr &
pkill xbindkeys; xbindkeys &

exec dwm

