call plug#begin('~/.vim/plugged')
call plug#end()


set path+=**
set showtabline=2
set foldignore=
set laststatus=1
set tabstop=8
set shiftwidth=8
set smarttab
set autoindent
set number
set relativenumber
set noswapfile 
set hlsearch
set incsearch
set linebreak
set background=dark
set foldmethod=indent
set nofoldenable
set cursorline
set paste
set noexpandtab
set nocompatible
syntax on




noremap K <nop>
noremap J <nop>

noremap ,s :set spell! spelllang=en,ru<CR>
noremap ,w :set list!<cr>
noremap ,c :execute "set colorcolumn=" . (&colorcolumn == "" ? "80" : "")<cr>
vnoremap <c-y> "yy <Bar> :call system('xclip -selection clipboard', @y)<cr>




" show whitespaces
set listchars=tab:>-,space:·,eol:~

" Unicode characters support
set fileencoding=utf-8
set encoding=utf-8
set termencoding=utf-8

" Russian language support
set langmap=ФИСВУАПРШОЛДЬТЩЗЙКЫЕГМЦЧНЯ;ABCDEFGHIJKLMNOPQRSTUVWXYZ,фисвуапршолдьтщзйкыегмцчня;abcdefghijklmnopqrstuvwxyz

" return to the same line you left off at
augroup line_return
	au!
	au BufReadPost *
		\ if line("'\"") > 0 && line("'\"") <= line("$") |
		\	execute 'normal! g`"zvzz' |
		\ endif
augroup END




highlight normal ctermfg=none
highlight visual ctermfg=none ctermbg=none cterm=reverse
highlight nontext ctermfg=white
highlight specialkey ctermfg=white
highlight search cterm=underline ctermfg=red ctermbg=none
highlight incsearch cterm=underline ctermfg=red ctermbg=none
highlight linenr term=none cterm=none ctermfg=yellow ctermbg=none
highlight cursorlinenr ctermfg=yellow ctermbg=none cterm=underline
highlight cursorline ctermfg=none ctermbg=none cterm=none
highlight cursorcolumn ctermfg=none ctermbg=none cterm=none
highlight colorcolumn ctermbg=cyan
highlight folded ctermfg=blue ctermbg=none
highlight TabLine ctermbg=none ctermfg=cyan cterm=none
highlight TabLineFill ctermbg=none ctermfg=cyan cterm=none
highlight TabLineSel ctermbg=cyan ctermfg=black cterm=none

