#!/bin/bash
while read file
do
    case "$1" in
    "d")
        rm "$file" ;;
    "i")
        convert -channel RGB -negate "$file" "$file" ;;
    "y")
        echo -n "$(realpath $file)" | xclip -selection clipboard ;;
    "Y")
        xclip -selection clipboard -t image/png -i $(realpath $file) ;;
    "w")
        xwallpaper --zoom "$file" ;;
    "e")
        mtpaint "$file" ;;
    esac
done

