
setxkbmap -layout us,ru -option grp:ctrl_space_toggle
echo -e "Sxiv.background: #222222\nSxiv.foreground: white" | xrdb -merge
xwallpaper --zoom $(ls ~/Pictures/wallpapers/* $([ -d /usr/share/backgrounds/xfce ] && echo /usr/share/backgrounds/xfce/*) | shuf | head -n1)
while true; do xsetroot -name " $(faw_dwm_panel) "; sleep 20s; done &
xcompmgr &
xbindkeys &
exec dwm

