#!/bin/bash

source ~/.bashrc

export EDITOR=vim
export _JAVA_AWT_WM_NONREPARENTING=1 # fix broken java apps in dwm

[ -d "$HOME/.local/bin" ]\
	&& PATH="$HOME/.local/bin:$PATH"

[ -f ~/.xinitrc ] && [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]\
	&& [[ -z "$TMUX" ]] && exec startx

