#!/bin/bash

[[ $- != *i* ]] && return # if not running interactively, don't do anything
stty -ixon # disable ctrl+s, ctrl+q
PS1="\[\e[0;1;30m\][\[\e[m\]\[\e[0;1;37m\]\W\[\e[m\]\[\e[0;1;30m\]]\[\e[m\] "

set -o vi
bind -m vi-command 'Control-l: clear-screen'
bind -m vi-insert 'Control-l: clear-screen'

alias l='ls --color --group-directories-first -p'
alias ll='clear; ls --color --group-directories-first -p -l -h -S'
alias la='ls --color --group-directories-first -p -a'
alias lla='clear; ls --color --group-directories-first -p -la -h -S'

alias mpv240="mpv --geometry=25%x25%-10-10 --ytdl-format='bestvideo[height<=?240]+bestaudio/best'"
alias mpv360="mpv --geometry=25%x25%-10-10 --ytdl-format='bestvideo[height<=?360]+bestaudio/best'"
alias mpv480="mpv --geometry=25%x25%-10-10 --ytdl-format='bestvideo[height<=?480]+bestaudio/best'"
alias mpv720="mpv --geometry=25%x25%-10-10 --ytdl-format='bestvideo[height<=?720]+bestaudio/best'"

alias yd240="yt-dlp --add-metadata -ic -f 'bestvideo[height<=240]+bestaudio/best[height<=240]'"
alias yd360="yt-dlp --add-metadata -ic -f 'bestvideo[height<=360]+bestaudio/best[height<=360]'"
alias yd480="yt-dlp --add-metadata -ic -f 'bestvideo[height<=480]+bestaudio/best[height<=480]'"
alias yd720="yt-dlp --add-metadata -ic -f 'bestvideo[height<=720]+bestaudio/best[height<=720]'"

alias webcam="ffplay -vf hflip /dev/video0"
alias tmx="tmux new-session -A -s default"
alias mki="sudo make clean && make && sudo make install"
alias nf="clear; fastfetch"
alias dl="aria2c"

function n {
	path=~/Documents/notes
	mkdir -p $path
	mkdir -p $path/todo.d

	today="$path/todo.d/$(date +'%y-%m-%d.txt')"
	tomorrow="$path/todo.d/$(date +'%y-%m-%d.txt' -d '+1 day')"
	yesterday="$path/todo.d/$(date +'%y-%m-%d.txt' -d '-1 day')"

	[ -f $today ] || faw_todo > $today
	[ -f $tomorrow ] || faw_todo > $tomorrow
	[ -f $yesterday ] || faw_todo > $yesterday
	$EDITOR -p $path/todo.md $path/todo.txt $path/study.md $yesterday $today $tomorrow
}

function cd {
	builtin cd "$@" && l
}

function gpp {
	msg="$@"
	[ -z "$msg" ] && echo 'need a commmit message' && return
	git add .
	git commit -m "$msg"
	git push
}

