#!/bin/bash

[[ $- != *i* ]] && return # if not running interactively, don't do anything

stty -ixon # disable ctrl+s, ctrl+q

PS1="\[\e[0;1;34m\][\[\e[m\]\[\e[0;1;37m\]\W\[\e[m\]\[\e[0;1;34m\]]\[\e[m\] "

set -o vi
bind -m vi-command 'Control-l: clear-screen'
bind -m vi-insert 'Control-l: clear-screen'

alias l='ls --color --group-directories-first -p'
alias ll='clear; ls --color --group-directories-first -p -l -h -S'
alias la='ls --color --group-directories-first -p -a'
alias lla='clear; ls --color --group-directories-first -p -la -h -S'

alias mpv240="mpv --geometry=25%x25%-10-10 --ytdl-format='bestvideo[height<=?240]+bestaudio/best'"
alias mpv360="mpv --geometry=25%x25%-10-10 --ytdl-format='bestvideo[height<=?360]+bestaudio/best'"
alias mpv480="mpv --geometry=25%x25%-10-10 --ytdl-format='bestvideo[height<=?480]+bestaudio/best'"
alias mpv720="mpv --geometry=25%x25%-10-10 --ytdl-format='bestvideo[height<=?720]+bestaudio/best'"

alias yd240="yt-dlp --add-metadata -ic -f 'bestvideo[height<=240]+bestaudio/best[height<=240]'"
alias yd360="yt-dlp --add-metadata -ic -f 'bestvideo[height<=360]+bestaudio/best[height<=360]'"
alias yd480="yt-dlp --add-metadata -ic -f 'bestvideo[height<=480]+bestaudio/best[height<=480]'"
alias yd720="yt-dlp --add-metadata -ic -f 'bestvideo[height<=720]+bestaudio/best[height<=720]'"

alias alm3="echo 'mpv ~/.alarm.mp3' | at 03:00 tomorrow"
alias alm4="echo 'mpv ~/.alarm.mp3' | at 04:00 tomorrow"
alias alm6="echo 'mpv ~/.alarm.mp3' | at 06:00 tomorrow"

alias webcam="ffplay -vf hflip /dev/video0"
alias tmx="tmux new-session -A -s default"
alias mki="sudo make clean && make && sudo make install"
alias nf="clear; neofetch"

function cd {
	builtin cd "$@" && l
}

function todo {
	for i in {00..23}; do
		for j in 00 20 40; do
			echo "$i:$j"
		done
	done
}

[ -z "$TMUX" ] && [ -n "$XTERM_VERSION" ] && [ -n "$(command -v transset)" ]\
	&& transset --id "$WINDOWID" >/dev/null 0.9

