
call plug#begin('~/.vim/plugged')
	Plug 'mkitt/tabline.vim'
	Plug 'christoomey/vim-system-copy'
	Plug 'faradayawerty/vim-monochrome'
call plug#end()

set number
set tabstop=6
set shiftwidth=6
set noswapfile 
set hlsearch
set incsearch
set ttimeout
set ttimeoutlen=10
set listchars=tab:>-,space:.,eol:~

syntax on
colorscheme monochrome

highlight TabLine ctermbg=none ctermfg=none cterm=none
highlight TabLineFill ctermbg=none ctermfg=gray cterm=none
highlight TabLineSel ctermbg=none ctermfg=white cterm=bold
highlight ColorColumn ctermbg=red

autocmd FileType c,cpp nnoremap <buffer> ,i :%!indent -ut -i8 -ts8 -l80 -nlp -npsl -br -ce -fca -npcs -nprs -nsaf -nsai -nsaw<cr>
autocmd FileType c,cpp vnoremap <buffer> ,i :!indent -ut -i8 -ts8 -l80 -nlp -npsl -br -ce -fca -npcs -nprs -nsaf -nsai -nsaw<cr>
autocmd FileType javascript,html nnoremap <buffer> ,i :%!js-beautify -t --wrap-line-length=80 --max-preserve-newlines=1 --brace-style=end-expand<cr>
autocmd FileType javascript,html vnoremap <buffer> ,i :!js-beautify -t --wrap-line-length=80 --max-preserve-newlines=1 --brace-style=end-expand<cr>

noremap ,S :set spell! spelllang=en,ru<cr>
noremap ,w :set list!<cr>
noremap ,p :set paste!<cr>
noremap ,c :execute "set colorcolumn=" . (&colorcolumn == "" ? "80" : "")<cr>
noremap <C-l> :noh<cr>

let g:system_copy_silent = 0

if executable('xclip')
	let g:system_copy#copy_command='xclip -sel clipboard'
	let g:system_copy#paste_command='xclip -sel clipboard -o'
endif

if has("win32") || has("win16")
	let g:system_copy#copy_command='clip'
	let g:system_copy#paste_command='paste'
endif

" return to the same line you left off at
augroup line_return
	au!
	au BufReadPost *
		\ if line("'\"") > 0 && line("'\"") <= line("$") |
		\	execute 'normal! g`"zvzz' |
		\ endif
augroup END

