
# -- general -- #
set global indentwidth 0
set global aligntab true
set global tabstop 6

add-highlighter global/ number-lines
add-highlighter global/ show-whitespaces
add-highlighter global/ column 80 default,red

face global MenuBackground yellow,default
face global MenuForeground black,yellow
face global PrimarySelection black,cyan
face global SecondarySelection black,magenta
face global Information yellow,default

# -- plugins -- #
nop %sh{
	mkdir -p "$kak_config/autoload"
	ln -s "$kak_runtime/autoload" "$kak_config/autoload/standard-library"
}

hook global WinCreate .* %{ kakboard-enable }

