#!/bin/bash
while read file
do
    case "$1" in
    "d")
        rm "$file" ;;
    "i")
        convert -channel RGB -negate "$file" "$file" ;;
    "y")
        echo -n "$(realpath $file)" | xclip -selection clipboard ;;
    "Y")
        xclip -selection clipboard -t image/png -i $(realpath $file) ;;
    "b")
        xwallpaper --zoom "$file"; cp "$file" ~/.wallpaper ;;
    "t")
        schemer_set_theme $file ;;
    esac
done

