#!/bin/bash

source ~/.bashrc

export EDITOR=nvim
export PAGER=less
export TERMINAL_BROWSER=w3m
export FILE_MANAGER=rover
export DOWNLOADER=aria2c
export MUSIC_PLAYER=cmus
export NEWS_READER=newsboat
export SOUND_MIXER=pulsemixer
export YOUTUBE_VIEWER=pipe-viewer

export TERMINAL=xterm
export BROWSER=chromium-browser
export OPEN=xdg-open
export DMENU=dmenu_xrdb
export RUNMENU=dmenu_launch
export MEDIA_PLAYER=mpv
export IMAGE_VIEWER=sxiv

export _JAVA_AWT_WM_NONREPARENTING=1 # fix broken java apps

export DEVPATH=~/dev
export GOPATH=$DEVPATH/lang_go
export CPATH=$DEVPATH/lang_c
export CPATH=$DEVPATH/lang_cpp
export PYPATH=$DEVPATH/lang_py
export LUAPATH=$DEVPATH/lang_lua
export JAVAPATH=$DEVPATH/lang_java

mkdir -p $CPATH
mkdir -p $PYPATH
mkdir -p $LUAPATH
mkdir -p $JAVAPATH

mkdir -p $GOPATH
mkdir -p $GOPATH/bin
mkdir -p $GOPATH/src
mkdir -p $GOPATH/pkg

if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

if [ -d "$GOPATH/bin" ] ; then
    PATH="$GOPATH/bin:$PATH"
fi

if [ -f ~/.xinitrc ] && [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]] && [[ -z "$TMUX" ]]; then exec startx; fi

