#!/bin/bash

# --- VARS --- #
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

# for setting history length see HISTSIZE and HISTFILESIZE
HISTSIZE=255
HISTFILESIZE=1023

# --- PROMPT --- #
PS1="\[\e[0;1;34m\][\[\e[m\]\[\e[0;1;33m\]\W\[\e[m\]\[\e[0;1;34m\]]\[\e[m\] "

# --- OPTIONS --- #
# append to the history file, don't overwrite it
shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# disable ctrl+s, ctrl+q
stty -ixon

# cd into directory by typing its name
#shopt -s autocd

# vi mode
#set -o vi
#bind -m vi-insert "\C-l":clear-screen

# --- ALIASES --- #
alias v="$EDITOR"
alias r="$FILE_MANAGER"
alias d="$DOWNLOADER"
alias nb="$NEWS_READER"
alias pm="$SOUND_MIXER"
alias ww="$TERMINAL_BROWSER duckduckgo.com/html"
alias wt="torsocks $TERMINAL_BROWSER duckduckgo.com/html"
alias ht='htop'
alias nf='clear; neofetch'
alias mk='sudo make clean && make && sudo make install'

alias gpp="git add .; git commit -m '-'; git push"
alias ga="git add ."
alias gc="git commit -m '-'"
alias gp="git push"

alias l='ls -Fh --color=auto --group-directories-first'
alias ll='clear;ls -lFh --color=auto --group-directories-first'
alias la='ls -aFh --color=auto --group-directories-first'
alias lla='clear;ls -laFh --color=auto --group-directories-first'

alias yt240="$YOUTUBE_VIEWER --resolution 240"
alias yt360="$YOUTUBE_VIEWER --resolution 360"
alias yt480="$YOUTUBE_VIEWER --resolution 480"
alias yt720="$YOUTUBE_VIEWER --resolution 720"

alias mpv240="mpv --geometry=25%x25%-10-10 --ytdl-format='bestvideo[height<=?240]+bestaudio/best'"
alias mpv360="mpv --geometry=25%x25%-10-10 --ytdl-format='bestvideo[height<=?360]+bestaudio/best'"
alias mpv480="mpv --geometry=25%x25%-10-10 --ytdl-format='bestvideo[height<=?480]+bestaudio/best'"
alias mpv720="mpv --geometry=25%x25%-10-10 --ytdl-format='bestvideo[height<=?720]+bestaudio/best'"

alias yd240="youtube-dl --add-metadata -ic -f 'bestvideo[height<=240]+bestaudio/best[height<=240]'"
alias yd360="youtube-dl --add-metadata -ic -f 'bestvideo[height<=360]+bestaudio/best[height<=360]'"
alias yd480="youtube-dl --add-metadata -ic -f 'bestvideo[height<=480]+bestaudio/best[height<=480]'"
alias yd720="youtube-dl --add-metadata -ic -f 'bestvideo[height<=720]+bestaudio/best[height<=720]'"

# --- FUNCTIONS --- #
function tm {
	session_name="$@"
	[ -z "$session_name" ] && session_name=default
	tmux new-session -A -s $session_name
}

function todo {
	for i in {00..23}; do
		for j in 00 20 40; do
			echo "$i:$j"
		done
	done
}

function cd {
	builtin cd "$@" && l
}

function aur {
	git clone https://aur.archlinux.org/$1.git
}

function wth {
	curl wttr.in/$1
}

# xterm transparency using transset
[ -z "$TMUX" ] && [ -n "$XTERM_VERSION" ] && transset --id "$WINDOWID" 0.9 >/dev/null

