#!/bin/bash

export EDITOR=kak
export PAGER=w3m
export TERMINAL_BROWSER=w3m
export DOWNLOADER=aria2c

export TERMINAL=st
export BROWSER=chromium
export DMENU=dmenu_xrdb
export RUNMENU=dmenu_launch
export MEDIA_PLAYER=mpv

export _JAVA_AWT_WM_NONREPARENTING=1 # fix broken java apps in dwm

export DEVPATH=~/dev
export GOPATH=$DEVPATH/lang_go
export CPATH=$DEVPATH/lang_c
export CPATH=$DEVPATH/lang_cpp
export PYPATH=$DEVPATH/lang_py
export LUAPATH=$DEVPATH/lang_lua
export JAVAPATH=$DEVPATH/lang_java

mkdir -p $CPATH
mkdir -p $PYPATH
mkdir -p $LUAPATH
mkdir -p $JAVAPATH

mkdir -p $GOPATH
mkdir -p $GOPATH/bin
mkdir -p $GOPATH/src
mkdir -p $GOPATH/pkg

if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

if [ -d "$GOPATH/bin" ] ; then
    PATH="$GOPATH/bin:$PATH"
fi

source ~/.bashrc

if [ -f ~/.xinitrc ] && [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]] && [[ -z "$TMUX" ]]; then
	exec startx
fi

