#! /bin/bash

mkdir -p ~/.config/qutebrowser
mkdir -p ~/.config/sxiv/exec

ln -snf $(realpath xinitrc) ~/.xinitrc
#ln -snf $(realpath xresources) ~/.Xresources
#ln -snf $(realpath sxiv/key-handler) ~/.config/sxiv/exec/key-handler
ln -snf $(realpath qutebrowser/config.py) ~/.config/qutebrowser/config.py

