# --- general --- #
add-highlighter global/ number-lines
#add-highlighter global/ column 80 black,green
set global ui_options ncurses_enable_mouse=false
set global indentwidth 0

# --- keys --- #
## clipboard integration
hook global NormalKey y|d|c %{ nop %sh{
      printf %s "$kak_main_reg_dquote" | xclip -i -selection clipboard >&- 2>&-
}}


# --- appearance --- #
## some color tweaks
face global MenuBackground yellow,default
face global MenuForeground black,yellow
face global PrimarySelection black,blue
face global SecondarySelection black,cyan


# --- dev --- #
## enable C/C++ completion with clang
hook global WinSetOption filetype=(c|cpp) %{
	clang-enable-autocomplete
	clang-enable-diagnostics
}

hook global BufWritePost .*\.(c|cpp) %{
	clang-parse
}


# --- plugins --- #
nop %sh{
	mkdir -p "$kak_config/autoload"
	ln -s "$kak_runtime/autoload" "$kak_config/autoload/standard-library"
}



