# set wallpaper
xwallpaper --stretch ~/.wallpaper

# enable transparency
#[ -f ~/.wallpaper ] && xcompmgr &

# set keyboard layout
#setxkbmap -layout us,ru -option grp:win_space_toggle
setxkbmap -layout us,ru -option grp:alt_shift_toggle

# x resources
xrdb ~/.Xresources

# dwm status
while true
do
	xsetroot -name " $(date +'%a %b %d %H:%M') "
	sleep 20s
done &

# start window manager
exec dwm

