# enable transparency if there's a wallpaper
[ -f ~/.wallpaper ] && xcompmgr &

# set keyboard layout
setxkbmap -layout us,ru -option grp:win_space_toggle

# load xresources
xrdb ~/.Xresources

# set colorscheme
wal -R -n

# set wallpaper
[ -f ~/.wallpaper ] && xwallpaper --stretch ~/.wallpaper

# dwm status
while true
do
	block_date=$(date +'%a %b %d %H:%M')
	block_temp=$(acpi -t | head -n1 | awk '{print $4}')
	block_memr=$(free -h | grep Mem | awk '{print $3 "/" $2}')
	xsetroot -name " $block_memr | $block_temp °C | $block_date "
	sleep 20s
done &

# start window manager
exec dwm

