# set wallpaper
xwallpaper --stretch ~/.wallpaper

# enable transparency
[ -f ~/.wallpaper ] && xcompmgr &

# set keyboard layout
#setxkbmap -layout us,ru -option grp:win_space_toggle
setxkbmap -layout us,ru -option grp:alt_shift_toggle

# dwm status
#while true
#do
#	xsetroot -name " $(date +'%d %b %Y %a %H:%M') "
#	sleep 40
#done &

# x resources
xrdb ~/.Xresources

# start window manager
exec i3

