#!/bin/bash

bupath=~/.cache/faw_backup/xorgrice
mkdir -p $bupath
cp ~/.wallpaper.jpg $bupath/wallpaper.jpg
echo -e "\nnote: xorgrice backups are stored at $bupath\n"

mkdir -p ~/.config/sxiv/exec
ln -snf $(realpath wallpaper.jpg) ~/.wallpaper.jpg
ln -snf /usr/local/share/sxiv/exec/sxiv_key-handler ~/.config/sxiv/exec/key-handler

cd suckless
./deploy
cd ..

