#!/bin/bash

source ~/.bashrc

export EDITOR=kak
export DMENU="rofi -dmenu"
export GOPATH=~/.go
export _JAVA_AWT_WM_NONREPARENTING=1 # fix broken java apps in dwm

if [ -d "$HOME/.local/bin" ]; then
	PATH="$HOME/.local/bin:$PATH"
fi

if [ -f ~/.xinitrc ] && [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]] && [[ -z "$TMUX" ]]; then
	exec startx
fi

