#!/bin/bash

[[ $- != *i* ]] && return # if not running interactively, don't do anything

stty -ixon # disable ctrl+s, ctrl+q

PS1="\[\e[0;1;34m\][\[\e[m\]\[\e[0;1;33m\]\W\[\e[m\]\[\e[0;1;34m\]]\[\e[m\] "

set -o vi
bind -m vi-command 'Control-l: clear-screen'
bind -m vi-insert 'Control-l: clear-screen'

alias nf='clear; neofetch --ascii_distro'
alias tmx='tmux new-session -A -s default'
alias mki='sudo make clean && make && sudo make install'
alias gpp="git add .; git commit -m '-'; git push"
alias webcam="ffplay -vf hflip /dev/video0"

alias mn='pmount'
alias um='pumount'

alias l='ls -p'
alias ll='clear; ls -p -l'
alias la='ls -p -a'
alias lla='clear; ls -p -la'

alias pv240='tmux rename-window "youtube(240p)" && pipe-viewer --resolution 240'
alias pv360='tmux rename-window "youtube(360p)" && pipe-viewer --resolution 360'
alias pv480='tmux rename-window "youtube(480p)" && pipe-viewer --resolution 480'
alias pv720='tmux rename-window "youtube(720p)" && pipe-viewer --resolution 720'

alias mpv240="mpv --geometry=25%x25%-10-10 --ytdl-format='bestvideo[height<=?240]+bestaudio/best'"
alias mpv360="mpv --geometry=25%x25%-10-10 --ytdl-format='bestvideo[height<=?360]+bestaudio/best'"
alias mpv480="mpv --geometry=25%x25%-10-10 --ytdl-format='bestvideo[height<=?480]+bestaudio/best'"
alias mpv720="mpv --geometry=25%x25%-10-10 --ytdl-format='bestvideo[height<=?720]+bestaudio/best'"

alias yd240="yt-dlp --add-metadata -ic -f 'bestvideo[height<=240]+bestaudio/best[height<=240]'"
alias yd360="yt-dlp --add-metadata -ic -f 'bestvideo[height<=360]+bestaudio/best[height<=360]'"
alias yd480="yt-dlp --add-metadata -ic -f 'bestvideo[height<=480]+bestaudio/best[height<=480]'"
alias yd720="yt-dlp --add-metadata -ic -f 'bestvideo[height<=720]+bestaudio/best[height<=720]'"

function cd {
	builtin cd "$@" && l
}

function todo {
	for i in {00..23}; do
		for j in 00 20 40; do
			echo "$i:$j"
		done
	done
}

function td {
	tmux rename-window 'todo'
	todo_dir=~/Notes/todo.d
	general_todo_file=~/Notes/todo.md
	tasks_file=~/Notes/tasks.md
	mkdir -p $todo_dir
	today_file=$todo_dir/$(date +'%Y-%m-%d')
	next_day_file=$todo_dir/$(date -d '+1 day' +'%Y-%m-%d')
	prev_day_file=$todo_dir/$(date -d '-1 day' +'%Y-%m-%d')
	[ -f $today_file ] || todo > $today_file
	[ -f $next_day_file ] || todo > $next_day_file
	[ -f $prev_day_file ] || todo > $prev_day_file
	vim -p $general_todo_file $tasks_file $prev_day_file $today_file $next_day_file
}

#[ -n "$(command -v transset)" ] && [ -z "$TMUX" ] && [ -n "$XTERM_VERSION" ] && transset --id "$WINDOWID" 0.9 > /dev/null

