
call plug#begin('~/.vim/plugged')
	Plug 'christoomey/vim-system-copy'
	Plug 'mkitt/tabline.vim'
	Plug 'prabirshrestha/vim-lsp'
	Plug 'prabirshrestha/asyncomplete.vim'
	Plug 'prabirshrestha/asyncomplete-lsp.vim'
	Plug 'OmniSharp/omnisharp-vim'
	Plug 'vim-skk/skk.vim'
call plug#end()

set path+=**
set showtabline=1
set foldignore=
set laststatus=1
set tabstop=6
set shiftwidth=6
set noexpandtab
set smarttab
set noautoindent
set number
set norelativenumber
set noswapfile 
set hlsearch
set incsearch
set linebreak
set foldmethod=indent
set nofoldenable
set nocursorline
set nopaste
set ttimeout
set ttimeoutlen=10
set fileencoding=utf-8
set encoding=utf-8
set termencoding=utf-8
set listchars=tab:>-,space:.,eol:~
set completeopt-=preview
set langmap=ФИСВУАПРШОЛДЬТЩЗЙКЫЕГМЦЧНЯ;ABCDEFGHIJKLMNOPQRSTUVWXYZ,фисвуапршолдьтщзйкыегмцчня;abcdefghijklmnopqrstuvwxyz

" return to the same line you left off at
augroup line_return
	au!
	au BufReadPost *
		\ if line("'\"") > 0 && line("'\"") <= line("$") |
		\	execute 'normal! g`"zvzz' |
		\ endif
augroup END

noremap ,S :set spell! spelllang=en,ru<CR>
noremap ,w :set list!<cr>
noremap ,p :set paste!<cr>
noremap ,c :execute "set colorcolumn=" . (&colorcolumn == "" ? "80" : "")<cr>
noremap gd :LspDefinition<cr>

autocmd FileType cs noremap gd :OmniSharpGotoDefinition<cr>
autocmd FileType tex set tabstop=2
autocmd FileType tex set expandtab
autocmd FileType tex set shiftwidth=2

let g:system_copy_silent = 0
let g:lsp_diagnostics_enabled = 1
let g:OmniSharp_server_use_mono = 1
let g:skk_large_jisyo = '/usr/share/skk/SKK-JISYO.L'

if executable('xclip')
	let g:system_copy#copy_command='xclip -sel clipboard'
	let g:system_copy#paste_command='xclip -sel clipboard -o'
endif

if has("win32") || has("win16")
	let g:system_copy#copy_command='clip'
	let g:system_copy#paste_command='paste'
endif

if executable('clangd')
   au User lsp_setup call lsp#register_server({
      \ 'name': 'clangd',
      \ 'cmd': {server_info->['clangd']},
      \ 'whitelist': ['c', 'cpp', 'objc', 'objcpp', 'cc', 'h', 'hpp'],
      \ })
endif

if executable('gopls')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'gopls',
        \ 'cmd': {server_info->['gopls']},
        \ 'allowlist': ['go'],
        \ })
endif

if executable('pyls')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'pyls',
        \ 'cmd': {server_info->['pyls']},
        \ 'allowlist': ['python'],
        \ })
endif

if exists('$TMUX')
	set t_Co=16
	set notermguicolors
	set background=dark
	syntax on
	colorscheme torte
	highlight Visual ctermfg=black ctermbg=cyan cterm=none
	highlight LineNr ctermfg=yellow ctermbg=none cterm=none
	highlight search cterm=none ctermbg=none ctermfg=none
	highlight incsearch cterm=underline ctermbg=none ctermfg=red
	highlight cursorline ctermfg=none ctermbg=none cterm=none
	highlight cursorlinenr cterm=bold
	highlight TabLine ctermbg=none ctermfg=none cterm=none
	highlight TabLineFill ctermfg=white ctermbg=none cterm=none
	highlight TabLineSel ctermfg=black ctermbg=blue cterm=none
	highlight Pmenu ctermfg=white ctermbg=darkgrey cterm=none
	highlight PmenuSel ctermfg=white ctermbg=darkgrey cterm=reverse
	highlight PmenuSbar ctermfg=white ctermbg=darkgrey cterm=none
	highlight PmenuThumb ctermfg=white ctermbg=darkgrey cterm=reverse
	highlight colorcolumn ctermbg=red
	highlight folded ctermfg=grey ctermbg=none
	highlight markdownError guifg=NONE guibg=black
endif

