#! /bin/bash

mkdir -p ~/.config/nvim
mkdir -p ~/.newsboat

ln -snf $(realpath tmux.conf) ~/.tmux.conf
ln -snf $(realpath bashrc) ~/.bashrc
ln -snf $(realpath bash_profile) ~/.bash_profile
ln -snf $(realpath newsboat/config) ~/.newsboat/config
ln -snf $(realpath neovim/init.vim) ~/.config/nvim/init.vim

