#!/bin/bash

# key handler for sxiv

while read file
do
    case "$1" in
    "d")
        rm "$file" ;;
    "i")
        convert -channel RGB -negate "$file" "$file" ;;
    "y")
        echo -n "$(realpath $file)" | xclip -selection clipboard ;;
	"Y")
		xclip -selection clipboard -t image/png -i $(realpath $file) ;;
    "b")
        xwallpaper --stretch "$file"; cp "$file" ~/.wallpaper ;;
    esac
done

