#!/bin/bash

export EDITOR=vim
export DMENU="rofi -dmenu"

export _JAVA_AWT_WM_NONREPARENTING=1 # fix broken java apps in dwm

if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# my directory structure
mkdir -p ~/Pictures/images
mkdir -p ~/Pictures/photo
mkdir -p ~/Tech/gaming
mkdir -p ~/Tech/devel
mkdir -p ~/Downloads
mkdir -p ~/Documents
mkdir -p ~/Music
mkdir -p ~/Notes
mkdir -p ~/Uni

source ~/.bashrc

if [ -f ~/.xinitrc ] && [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]] && [[ -z "$TMUX" ]]; then
	exec startx
fi

