" plugins
call plug#begin('~/.vim/plugged')
	Plug 'fxn/vim-monochrome'
	Plug 'prabirshrestha/asyncomplete.vim'
	Plug 'prabirshrestha/vim-lsp'
	Plug 'prabirshrestha/asyncomplete-lsp.vim'
call plug#end()

colorscheme monochrome

if executable('clangd')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'clangd',
        \ 'cmd': {server_info->['clangd', '-background-index']},
        \ 'whitelist': ['c', 'cpp', 'objc', 'objcpp'],
        \ })
endif

set path+=**
set showtabline=1
set foldignore=
set laststatus=1
set tabstop=5
set shiftwidth=5
set smarttab
set autoindent
set number
set norelativenumber
set noswapfile 
set hlsearch
set incsearch
set linebreak
set background=dark
set foldmethod=indent
set nofoldenable
set cursorline
set noexpandtab
set paste
set guicursor=
syntax on

set listchars=tab:>-,space:·,eol:~

set fileencoding=utf-8
set encoding=utf-8
set termencoding=utf-8

let mapleader=","
noremap <leader>S :set spell! spelllang=en,ru<CR>
noremap <leader>w :set list!<cr>
noremap <leader>p :set paste!<cr>
noremap <leader>c :execute "set colorcolumn=" . (&colorcolumn == "" ? "80" : "")<cr>

set langmap=ФИСВУАПРШОЛДЬТЩЗЙКЫЕГМЦЧНЯ;ABCDEFGHIJKLMNOPQRSTUVWXYZ,фисвуапршолдьтщзйкыегмцчня;abcdefghijklmnopqrstuvwxyz

" return to the same line you left off at
augroup line_return
	au!
	au BufReadPost *
		\ if line("'\"") > 0 && line("'\"") <= line("$") |
		\	execute 'normal! g`"zvzz' |
		\ endif
augroup END

highlight TabLine ctermbg=none ctermfg=blue cterm=none
highlight TabLineFill ctermbg=none ctermfg=grey cterm=none
highlight TabLineSel ctermbg=blue ctermfg=black cterm=none
highlight search cterm=underline ctermbg=none
highlight incsearch cterm=underline ctermbg=none
highlight cursorline ctermfg=none ctermbg=none cterm=none
highlight colorcolumn ctermbg=red
highlight folded ctermfg=grey ctermbg=none

