
call plug#begin('~/.vim/plugged')
	Plug 'fxn/vim-monochrome'
	Plug 'christoomey/vim-system-copy'
	Plug 'prabirshrestha/vim-lsp'
	Plug 'prabirshrestha/asyncomplete.vim'
	Plug 'prabirshrestha/asyncomplete-lsp.vim'
call plug#end()

if executable('eclipse-jdt-lsp')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'eclipse-jdt-lsp',
        \ 'cmd': {server_info->['eclipse-jdt-lsp']},
        \ 'allowlist': ['java'],
        \ })
endif

if executable('pyls')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'pyls',
        \ 'cmd': {server_info->['pyls']},
        \ 'allowlist': ['python'],
        \ })
endif

if executable('clangd')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'clangd',
        \ 'cmd': {server_info->['clangd', '-background-index']},
        \ 'whitelist': ['c', 'cpp', 'objc', 'objcpp'],
        \ })
endif

let g:system_copy#copy_command='xclip -sel clipboard'
let g:system_copy#paste_command='xclip -sel clipboard -o'
let g:system_copy_silent = 1

colorscheme monochrome
syntax on
set path+=**
set showtabline=1
set foldignore=
set laststatus=1
set tabstop=5
set shiftwidth=5
set smarttab
set autoindent
set number
set norelativenumber
set noswapfile 
set hlsearch
set incsearch
set linebreak
set background=dark
set foldmethod=indent
set nofoldenable
set cursorline
set noexpandtab
set paste
set ttimeout
set ttimeoutlen=10
set listchars=tab:>-,space:·,eol:~
set fileencoding=utf-8
set encoding=utf-8
set termencoding=utf-8
set langmap=ФИСВУАПРШОЛДЬТЩЗЙКЫЕГМЦЧНЯ;ABCDEFGHIJKLMNOPQRSTUVWXYZ,фисвуапршолдьтщзйкыегмцчня;abcdefghijklmnopqrstuvwxyz

let mapleader=","
noremap <leader>S :set spell! spelllang=en,ru<CR>
noremap <leader>w :set list!<cr>
noremap <leader>p :set paste!<cr>
noremap <leader>c :execute "set colorcolumn=" . (&colorcolumn == "" ? "80" : "")<cr>

noremap gd :LspDefinition<cr>

" return to the same line you left off at
augroup line_return
	au!
	au BufReadPost *
		\ if line("'\"") > 0 && line("'\"") <= line("$") |
		\	execute 'normal! g`"zvzz' |
		\ endif
augroup END

highlight TabLine ctermbg=none ctermfg=blue cterm=none
highlight TabLineFill ctermbg=none ctermfg=grey cterm=none
highlight TabLineSel ctermbg=blue ctermfg=black cterm=none
highlight search cterm=underline ctermbg=none
highlight incsearch cterm=underline ctermbg=none
highlight cursorline ctermfg=none ctermbg=none cterm=none
highlight colorcolumn ctermbg=red
highlight folded ctermfg=grey ctermbg=none

