# general configuration
    # enable running cd by typing the name of a directory 
    setopt autocd autopushd

    # disable ctrl+s, ctrl+q
    stty -ixon
	autoload -U colors && colors

    # vi mode
    bindkey -v

    # prompt
        # no colors
        #PROMPT="%~ "

        # colors
        #PROMPT="%B%F{blue}(%f%b%B%F{yellow}%~%f%b%B%F{blue})%f%b %B%F{red}%#%f%b "
        PROMPT="%B%F{blue}[%f%b%B%F{yellow}%~%f%b%B%F{blue}]%f%b "
        #PROMPT="%F{blue}[%f%F{yellow}%~%f%F{blue}]%f "

    # completion
        autoload -Uz compinit 
        compinit
        zstyle ':completion:*' menu select
        zmodload zsh/complist
        _comp_options+=(globdots) # Include hidden files in autocomplete:

    ## from luke smith's config vim-like movement
        bindkey -M menuselect 'h' vi-backward-char
        bindkey -M menuselect 'k' vi-up-line-or-history
        bindkey -M menuselect 'l' vi-forward-char
        bindkey -M menuselect 'j' vi-down-line-or-history
    ## END from luke smith's config

    # autosuggestions and syntax highlighting
    source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
    ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=4"

    # history
    setopt INC_APPEND_HISTORY
    HISTFILE="$HOME/.zsh_history"
    HISTSIZE=65535
    SAVEHIST=65535

# useful functions
    # weather function
    # depends on curl
    function weather { clear;curl wttr.in/$1 }

    # little aur helper
    function aur-get { git clone https://aur.archlinux.org/"$1".git }

# aliases
    # ls aliases
    alias l='ls -Fh --sort=version --color=auto'
    alias ll='ls -lFh --sort=version --color=auto'
    alias la='ls -aFh --sort=version --color=auto'
    alias lla='ls -laFh --sort=version --color=auto'
    #alias l='exa'
    #alias ll='exa -l'
    #alias la='exa -a'
    #alias lla='exa -la'
    #alias L='exa -G'
    #alias LL='exa -lG'
    #alias LA='exa -aG'
    #alias LLA='exa -laG'

    # automatically list files when changing directory
    chpwd() l

    # youtube-dl and mpv aliases
    alias yd='youtube-dl --add-metadata -ic -f "bestvideo[height<=360]+bestaudio/best[height<=360]"'
    alias yd360='youtube-dl --add-metadata -ic -f "bestvideo[height<=360]+bestaudio/best[height<=360]"'
    alias yd480='youtube-dl --add-metadata -ic -f "bestvideo[height<=480]+bestaudio/best[height<=480]"'
    alias yd720='youtube-dl --add-metadata -ic -f "bestvideo[height<=720]+bestaudio/best[height<=720]"'

    alias mpv720='mpv --ytdl-format="bestvideo[height<=?720]+bestaudio/best"'
    alias mpv480='mpv --ytdl-format="bestvideo[height<=?480]+bestaudio/best"'
    alias mpv360='mpv --ytdl-format="bestvideo[height<=?360]+bestaudio/best"'

    # full-word aliases
    alias editor='$EDITOR'
    alias clock='tty-clock -sc -C4'

    # 1-2 letter aliases
    alias e=editor
    alias ht=htop
    alias nb=newsboat
    alias pm=pulsemixer

    # set default options for some commands
    alias sxiv="sxiv -obt"

# keybindings
    # up
        function up_widget() { BUFFER="cd .."; zle accept-line }
        zle -N up_widget
        bindkey "^u" up_widget

    # paste from clipboard
        function clipboard_widget() { BUFFER="$BUFFER$(xclip -selection clipboard -o)" }
        zle -N clipboard_widget
        bindkey "^v" clipboard_widget
