#!/bin/bash

cd /tmp
mkdir kak-lsp-install
cd kak-lsp-install

wget https://github.com/kak-lsp/kak-lsp/releases/download/v11.0.0/kak-lsp-v11.0.0-x86_64-unknown-linux-musl.tar.gz
tar xzvf kak-lsp-v11.0.0-x86_64-unknown-linux-musl.tar.gz

mv kak-lsp ~/.local/bin/

